[debug] [2025-04-28T01:01:21.197Z] [Firebase Plugin] Activating Firebase extension.
[debug] [2025-04-28T01:01:21.742Z] [Firebase Plugin] requireAuthWrapper
[debug] [2025-04-28T01:01:21.742Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2025-04-28T01:01:21.743Z] > authorizing via signed-in user (javier@alzares.cl)
[debug] [2025-04-28T01:01:21.745Z] Checked if tokens are valid: false, expires at: 1745710666104
[debug] [2025-04-28T01:01:21.746Z] Checked if tokens are valid: false, expires at: 1745710666104
[debug] [2025-04-28T01:01:21.746Z] > refreshing access token with scopes: []
[debug] [2025-04-28T01:01:21.747Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2025-04-28T01:01:21.747Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2025-04-28T01:01:21.755Z] [Firebase Plugin] VSCode notification server listening on port 40001
[info] [Firebase Plugin] Starting Data Connect toolkit (version 2.2.0) on port 50001
[info] i  dataconnect: downloading dataconnect-emulator-2.2.0... {"metadata":{"emulator":{"name":"dataconnect"},"message":"downloading dataconnect-emulator-2.2.0..."}}
[debug] [2025-04-28T01:01:21.969Z] >>> [apiv2][query] GET https://storage.googleapis.com/firemat-preview-drop/emulator/dataconnect-emulator-linux-v2.2.0 
[debug] [2025-04-28T01:01:22.048Z] <<< [apiv2][status] POST https://www.googleapis.com/oauth2/v3/token 400
[debug] [2025-04-28T01:01:22.048Z] <<< [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[error] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[error] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[error] [Firebase Plugin] requireAuth error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2025-04-28T01:01:22.402Z] <<< [apiv2][status] GET https://storage.googleapis.com/firemat-preview-drop/emulator/dataconnect-emulator-linux-v2.2.0 200
[debug] [2025-04-28T01:01:22.402Z] <<< [apiv2][body] GET https://storage.googleapis.com/firemat-preview-drop/emulator/dataconnect-emulator-linux-v2.2.0 [stream]
[info] i  dataconnect: Removing outdated emulator files: dataconnect-emulator-2.3.1 {"metadata":{"emulator":{"name":"dataconnect"},"message":"Removing outdated emulator files: dataconnect-emulator-2.3.1"}}
[debug] [2025-04-28T01:01:24.475Z] 'fdc build' failed with error: Unable to build your Data Connect schema and connectors (exit code 1): E0427 21:01:24.474580    6919 cmd.go:43] Error loading data connect config: could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"'fdc build' failed with error: Unable to build your Data Connect schema and connectors (exit code 1): E0427 21:01:24.474580    6919 cmd.go:43] Error loading data connect config: could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`\n"}}
[debug] [2025-04-28T01:01:24.476Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2025-04-28T01:01:24.476Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"dataconnect"},"message":"Ignoring unsupported arg: port"}}
[debug] [2025-04-28T01:01:24.476Z] Starting Data Connect Emulator with command {"binary":"/home/xavirodrigu/.cache/firebase/emulators/dataconnect-emulator-2.2.0","args":["--logtostderr","-v=2","dev","--listen=localhost:50001","--config_dir=/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect","--enable_output_schema_extensions=true","--enable_output_generated_sdk=true"],"optionalArgs":["listen","config_dir","enable_output_schema_extensions","enable_output_generated_sdk"],"joinArgs":true,"shell":false,"port":9399} {"metadata":{"emulator":{"name":"dataconnect"},"message":"Starting Data Connect Emulator with command {\"binary\":\"/home/xavirodrigu/.cache/firebase/emulators/dataconnect-emulator-2.2.0\",\"args\":[\"--logtostderr\",\"-v=2\",\"dev\",\"--listen=localhost:50001\",\"--config_dir=/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect\",\"--enable_output_schema_extensions=true\",\"--enable_output_generated_sdk=true\"],\"optionalArgs\":[\"listen\",\"config_dir\",\"enable_output_schema_extensions\",\"enable_output_generated_sdk\"],\"joinArgs\":true,\"shell\":false,\"port\":9399}"}}
[info] i  dataconnect: Data Connect Emulator logging to dataconnect-debug.log {"metadata":{"emulator":{"name":"dataconnect"},"message":"Data Connect Emulator logging to dataconnect-debug.log"}}
[debug] [2025-04-28T01:01:24.488Z] E0427 21:01:24.488376    6929 load.go:23] Could not load config from "/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0427 21:01:24.488376    6929 load.go:23] Could not load config from \"/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect\": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`\n"}}
[debug] [2025-04-28T01:01:24.489Z] I0427 21:01:24.488812    6929 dev.go:95] Listening on address (HTTP + gRPC): 127.0.0.1:50001
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"I0427 21:01:24.488812    6929 dev.go:95] Listening on address (HTTP + gRPC): 127.0.0.1:50001\n"}}
[error] [Firebase Plugin] error:  {}
[debug] [2025-04-28T01:01:34.497Z] E0427 21:01:34.496878    6929 load.go:23] Could not load config from "/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0427 21:01:34.496878    6929 load.go:23] Could not load config from \"/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect\": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`\n"}}
[debug] [2025-04-28T01:01:44.498Z] E0427 21:01:44.497928    6929 load.go:23] Could not load config from "/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0427 21:01:44.497928    6929 load.go:23] Could not load config from \"/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect\": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`\n"}}
[debug] [2025-04-28T01:01:54.494Z] E0427 21:01:54.493885    6929 load.go:23] Could not load config from "/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0427 21:01:54.493885    6929 load.go:23] Could not load config from \"/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect\": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`\n"}}
[debug] [2025-04-28T01:02:04.498Z] E0427 21:02:04.497780    6929 load.go:23] Could not load config from "/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0427 21:02:04.497780    6929 load.go:23] Could not load config from \"/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect\": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`\n"}}
[debug] [2025-04-28T01:02:14.498Z] E0427 21:02:14.497802    6929 load.go:23] Could not load config from "/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0427 21:02:14.497802    6929 load.go:23] Could not load config from \"/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect\": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`\n"}}
[debug] [2025-04-28T01:02:24.494Z] E0427 21:02:24.493964    6929 load.go:23] Could not load config from "/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0427 21:02:24.493964    6929 load.go:23] Could not load config from \"/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect\": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`\n"}}
[debug] [2025-04-28T01:02:34.498Z] E0427 21:02:34.497882    6929 load.go:23] Could not load config from "/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0427 21:02:34.497882    6929 load.go:23] Could not load config from \"/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect\": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`\n"}}
[debug] [2025-04-28T01:02:44.497Z] E0427 21:02:44.497754    6929 load.go:23] Could not load config from "/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0427 21:02:44.497754    6929 load.go:23] Could not load config from \"/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect\": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`\n"}}
[debug] [2025-04-28T01:02:54.494Z] E0427 21:02:54.493839    6929 load.go:23] Could not load config from "/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0427 21:02:54.493839    6929 load.go:23] Could not load config from \"/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect\": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`\n"}}
[debug] [2025-04-28T01:03:04.497Z] E0427 21:03:04.497754    6929 load.go:23] Could not load config from "/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0427 21:03:04.497754    6929 load.go:23] Could not load config from \"/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect\": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`\n"}}
[debug] [2025-04-28T01:03:14.498Z] E0427 21:03:14.497851    6929 load.go:23] Could not load config from "/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0427 21:03:14.497851    6929 load.go:23] Could not load config from \"/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect\": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`\n"}}
[debug] [2025-04-28T01:03:24.493Z] E0427 21:03:24.493778    6929 load.go:23] Could not load config from "/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0427 21:03:24.493778    6929 load.go:23] Could not load config from \"/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect\": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`\n"}}
[debug] [2025-04-28T01:03:34.489Z] E0427 21:03:34.488960    6929 load.go:23] Could not load config from "/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`
 {"metadata":{"emulator":{"name":"dataconnect"},"message":"E0427 21:03:34.488960    6929 load.go:23] Could not load config from \"/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect\": could not find dataconnect.yaml in `/home/xavirodrigu/alzares/40M/40-minutos-app/dataconnect`\n"}}
